export const ADD_STUDENTS_BYSCHOOLUSER_REQUEST = 'ADD_STUDENTS_BYSCHOOLUSER_REQUEST';
export const ADD_STUDENTS_BYSCHOOLUSER_SUCCESS = 'ADD_STUDENTS_BYSCHOOLUSER_SUCCESS';
export const ADD_STUDENTS_BYSCHOOLUSER_FAILURE = 'ADD_STUDENTS_BYSCHOOLUSER_FAILURE';