export const GET_STUDENTSNUMBERS_REQUEST = 'GET_STUDENTSNUMBERS_REQUEST';
export const GET_STUDENTSNUMBERS_SUCCESS = 'GET_STUDENTSNUMBERS_SUCCESS';
export const GET_STUDENTSNUMBERS_FAILURE = 'GET_STUDENTSNUMBERS_FAILURE';