export const GET_PRIMARYRESULTBY_ADMIN_REQUEST = 'GET_PRIMARYRESULTBY_ADMIN_REQUEST';
export const GET_PRIMARYRESULTBY_ADMIN_SUCCESS = 'GET_PRIMARYRESULTBY_ADMIN_SUCCESS';
export const GET_PRIMARYRESULTBY_ADMIN_FAILURE = 'GET_PRIMARYRESULTBY_ADMIN_FAILURE';