export const GET_STUDENTS_BYSCHOOLUSER_REQUEST = 'GET_STUDENTS_BYSCHOOLUSER_REQUEST';
export const GET_STUDENTS_BYSCHOOLUSER_SUCCESS = 'GET_STUDENTS_BYSCHOOLUSER_SUCCESS';
export const GET_STUDENTS_BYSCHOOLUSER_FAILURE = 'GET_STUDENTS_BYSCHOOLUSER_FAILURE';