export const GET_AVAILABLEEXAMSDONE_REQUEST = 'GET_AVAILABLEEXAMSDONE_REQUEST';
export const GET_AVAILABLEEXAMSDONE_SUCCESS = 'GET_AVAILABLEEXAMSDONE_SUCCESS';
export const GET_AVAILABLEEXAMSDONE_FAILURE = 'GET_AVAILABLEEXAMSDONE_FAILURE';