export const GET_EXAMS_BYLEVEL_REQUEST = 'GET_EXAMS_BYLEVEL_REQUEST';
export const GET_EXAMS_BYLEVEL_SUCCESS = 'GET_EXAMS_BYLEVEL_SUCCESS';
export const GET_EXAMS_BYLEVEL_FAILURE = 'GET_EXAMS_BYLEVEL_FAILURE';