export const GET_ORDINARYLEVELEXAMS_REQUEST = 'GET_ORDINARYLEVELEXAMS_REQUEST';
export const GET_ORDINARYLEVELEXAMS_SUCCESS = 'GET_ORDINARYLEVELEXAMS_SUCCESS';
export const GET_ORDINARYLEVELEXAMS_FAILURE = 'GET_ORDINARYLEVELEXAMS_FAILURE';