export const GET_PRIMARY_STUDENTS_REQUEST = 'GET_PRIMARY_STUDENTS_REQUEST';
export const GET_PRIMARY_STUDENTS_SUCCESS = 'GET_PRIMARY_STUDENTS_SUCCESS';
export const GET_PRIMARY_STUDENTS_FAILURE = 'GET_PRIMARY_STUDENTS_FAILURE';