export const GET_PRIMARYLEVEL_RESULTS_REQUEST = 'GET_PRIMARYLEVEL_RESULTS_REQUEST';
export const GET_PRIMARYLEVEL_RESULTS_SUCCESS = 'GET_PRIMARYLEVEL_RESULTS_SUCCESS';
export const GET_PRIMARYLEVEL_RESULTS_FAILURE = 'GET_PRIMARYLEVEL_RESULTS_FAILURE';