export const GET_QUESTION_BYID_REQUEST = 'GET_QUESTION_BYID_REQUEST';
export const GET_QUESTION_BYID_SUCCESS = 'GET_QUESTION_BYID_SUCCESS';
export const GET_QUESTION_BYID_FAILURE = 'GET_QUESTION_BYID_FAILURE';