export const GET_STUDENT_BYSCHOOLID_REQUEST = 'GET_STUDENT_BYSCHOOLID_REQUEST';
export const GET_STUDENT_BYSCHOOLID_SUCCESS = 'GET_STUDENT_BYSCHOOLID_SUCCESS';
export const GET_STUDENT_BYSCHOOLID_FAILURE = 'GET_STUDENT_BYSCHOOLID_FAILURE';